# -*- coding: utf-8 -*-
"""IOT_temp_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwF5GwbGV6tcuxwZCG2LEXqGPzTTiCUA
"""

# !pip install mysql.connector
# !pip install pandas bokeh pyproj
# import mysql.connector
# import pandas as pd
# import pandas as pd
# from bokeh.plotting import figure, output_file, show, output_notebook
# from bokeh.models import ColumnDataSource, LabelSet, HoverTool

#connecting to the web server
con=mysql.connector.connect(host='cnit5.tech.purdue.edu',user='powerTeam', password='CNIT581POWER', port='3306', database='project')
cursor=con.cursor(buffered=True)
cursor.execute("select database ();")
record=cursor.fetchone()
print("You're connected to database: ", record)

command3='select * from testTemp;'
cursor.execute(command3)
temp=[]
for row in cursor:
  temp.append(row)
cursor.close()
con.close()

#temp list to df and data clean
temp=pd.DataFrame(temp)
temp=temp.drop([0], axis=1)
temp[1]=pd.to_datetime(temp[1])

temp

#reformatting date and time
date=[]
hour=[]
min=[]
sec=[]
for i in range(0,len(temp)):
  date.append(temp.iloc[i][1].date())
  hour.append(temp.iloc[i][1].time().hour)
  min.append(temp.iloc[i][1].time().minute)
  sec.append(temp.iloc[i][1].time().second)

date=pd.DataFrame(date)
date.columns=["date"]
hour=pd.DataFrame(hour)
hour.columns=["hour"]
min=pd.DataFrame(min)
min.columns=["min"]
sec=pd.DataFrame(sec)
sec.columns=["sec"]
temp_F=pd.DataFrame(temp[2])
temp_F.columns=["temp_F"]
temp_C=pd.DataFrame(temp[3])
temp_C.columns=["temp_C"]

#creating updated df (removing first two rows as they were junk/mixed values)
temp_n=pd.concat([date, hour, min, sec, temp_F, temp_C], axis=1)
temp_n=temp_n.drop([0,1], axis=0)
temp_n = temp_n.reset_index(drop=True)

temp_n

from bokeh.models import ColumnDataSource, LabelSet, HoverTool
from collections import OrderedDict

#tempF interactive visualizations
output_notebook()
source = ColumnDataSource(temp_n)
tooltips = [
    ("temp_F", "@temp_F"),
]
p = figure(x_axis_type='datetime', tooltips=tooltips)
p.title.text = "Temperature"
p.title.align = "center"

p.line(x='date', y='temp_F', source=source, line_color="purple", line_width = 3, legend="Temp_F")
p.yaxis.axis_label = 'Temperature'

output_file("temp_line_chart.html", title="Temp Line Chart")
show(p)

#show last recorded temperature
print("Last recorded temperature was", temp_n['temp_F'].iloc[-1],"F on", temp_n['date'].iloc[-1], "at", temp_n['hour'].iloc[-1],":",temp_n['min'].iloc[-1],":",temp_n['sec'].iloc[-1]  )

temp_n.head()

#combining bokeh html objects to webpage
#http://docs.bokeh.org/en/1.3.2/docs/user_guide/embed.html